"""AgendaTracker — manages Principles/follow_up_agenda.md.

Each L2 cluster (direction consensus, numeric/severity disagreement) generates
0-2 agenda items:
  - Quantitative upgrade: "Y wants 10 yr, Layer 0 = 3 yr → Y论证升到 5 yr/10 yr"
  - Severity upgrade: "Y wants veto, Layer 0 = note → Y论证升到 warning/veto"

Agenda items have lifecycle:
  active → resolved (consensus reached in later mini-debate)
         → stale (4 quarters without resolution)
         → dormant (moved to soul-level-preferences as permanent disagreement)

File format: YAML frontmatter (JSON-compat) + human-readable body.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field, asdict
from datetime import datetime
from pathlib import Path
from typing import Optional

from scripts.soul.board import PRINCIPLES_DIR

DEFAULT_AGENDA_PATH = PRINCIPLES_DIR / "follow_up_agenda.md"

STALE_QUARTERS = 4  # after 4 un-resolved quarters, demote to dormant


@dataclass
class AgendaItem:
    item_id: str                   # e.g. "agenda_cl_10_quant_2026Q2"
    cluster_id: str
    item_type: str                 # "quant_upgrade" | "severity_upgrade"
    canonical_claim: str
    rule_subject: str
    current_layer0_value: str       # string repr of current threshold/severity
    proposed_by_master: dict       # {master: proposed value}
    proposed_rationale: dict        # {master: rationale string}
    created_at_debate_id: str
    status: str = "active"         # "active" | "resolved" | "stale" | "dormant"
    resolved_at_debate_id: Optional[str] = None
    resolution_note: Optional[str] = None
    quarters_unresolved: int = 0


class AgendaTracker:
    def __init__(self, agenda_path: Path = DEFAULT_AGENDA_PATH):
        self.agenda_path = agenda_path
        self.items: dict[str, AgendaItem] = {}
        self._load()

    # ─── Persistence ───

    def _load(self) -> None:
        if not self.agenda_path.exists():
            self.items = {}
            return
        text = self.agenda_path.read_text(encoding="utf-8")
        frontmatter_match = re.match(r"^---\s*\n(.*?)\n---\s*\n", text, re.DOTALL)
        if not frontmatter_match:
            self.items = {}
            return
        fm_text = frontmatter_match.group(1).strip()
        data = None
        # First try parsing as JSON directly (our writer emits JSON)
        try:
            data = json.loads(fm_text)
        except Exception:
            pass
        # Fallback: try wrapping (legacy format)
        if data is None:
            try:
                data = json.loads("{" + fm_text.replace("\n", " ") + "}")
            except Exception:
                pass
        # Last fallback: real yaml
        if data is None:
            try:
                import yaml  # type: ignore
                data = yaml.safe_load(fm_text) or {}
            except Exception:
                data = {}

        items_data = data.get("agenda_items", [])
        if not isinstance(items_data, list):
            return
        for d in items_data:
            if not isinstance(d, dict) or "item_id" not in d:
                continue
            item = AgendaItem(
                item_id=d.get("item_id"),
                cluster_id=d.get("cluster_id", ""),
                item_type=d.get("item_type", "quant_upgrade"),
                canonical_claim=d.get("canonical_claim", ""),
                rule_subject=d.get("rule_subject", "target"),
                current_layer0_value=d.get("current_layer0_value", ""),
                proposed_by_master=d.get("proposed_by_master") or {},
                proposed_rationale=d.get("proposed_rationale") or {},
                created_at_debate_id=d.get("created_at_debate_id", ""),
                status=d.get("status", "active"),
                resolved_at_debate_id=d.get("resolved_at_debate_id"),
                resolution_note=d.get("resolution_note"),
                quarters_unresolved=d.get("quarters_unresolved", 0),
            )
            self.items[item.item_id] = item

    def save(self) -> None:
        self.agenda_path.parent.mkdir(parents=True, exist_ok=True)
        frontmatter = json.dumps(
            {"agenda_items": [asdict(v) for v in self.items.values()]},
            ensure_ascii=False, indent=2,
        )
        body = self._render_body()
        self.agenda_path.write_text(f"---\n{frontmatter}\n---\n\n{body}", encoding="utf-8")

    def _render_body(self) -> str:
        lines = ["# Follow-up Agenda", "",
                 f"> Auto-generated by `board/agenda_tracker.py`",
                 f"> Last updated: {datetime.now().isoformat(timespec='seconds')}",
                 "",
                 f"Active items: {sum(1 for v in self.items.values() if v.status == 'active')}",
                 f"Resolved items: {sum(1 for v in self.items.values() if v.status == 'resolved')}",
                 f"Stale items: {sum(1 for v in self.items.values() if v.status == 'stale')}",
                 f"Dormant items: {sum(1 for v in self.items.values() if v.status == 'dormant')}",
                 "", "---", ""]
        active = [v for v in self.items.values() if v.status == "active"]
        if active:
            lines.append("## 🟢 Active")
            for item in sorted(active, key=lambda x: x.cluster_id):
                lines.extend(self._render_item(item))
        resolved = [v for v in self.items.values() if v.status == "resolved"]
        if resolved:
            lines.append("## ✅ Resolved")
            for item in sorted(resolved, key=lambda x: x.cluster_id):
                lines.extend(self._render_item(item))
        stale = [v for v in self.items.values() if v.status == "stale"]
        if stale:
            lines.append("## 🟡 Stale (may demote to dormant)")
            for item in sorted(stale, key=lambda x: x.cluster_id):
                lines.extend(self._render_item(item))
        dormant = [v for v in self.items.values() if v.status == "dormant"]
        if dormant:
            lines.append("## ⚪ Dormant (permanent disagreement)")
            for item in sorted(dormant, key=lambda x: x.cluster_id):
                lines.extend(self._render_item(item))
        return "\n".join(lines)

    def _render_item(self, item: AgendaItem) -> list[str]:
        out = [
            f"### {item.item_id}",
            f"- **cluster**: {item.cluster_id}",
            f"- **type**: {item.item_type}",
            f"- **claim**: {item.canonical_claim[:80]}...",
            f"- **current_layer0**: {item.current_layer0_value}",
            f"- **proposed by**:",
        ]
        for m, v in item.proposed_by_master.items():
            rat = item.proposed_rationale.get(m, "")
            out.append(f"  - `{m}`: {v} — {rat[:80]}")
        out.append(f"- **created_at**: {item.created_at_debate_id}")
        if item.resolved_at_debate_id:
            out.append(f"- **resolved_at**: {item.resolved_at_debate_id}")
            out.append(f"- **resolution**: {item.resolution_note}")
        out.append("")
        return out

    # ─── Core operations ───

    def add_quant_upgrade(self, cluster_id: str, current_threshold,
                          proposed_by_master: dict, proposed_rationale: dict,
                          canonical_claim: str, rule_subject: str,
                          current_debate_id: str) -> str:
        """Register a quantitative upgrade proposal. Returns item_id."""
        year_quarter = self._year_quarter_from_debate_id(current_debate_id)
        item_id = f"agenda_{cluster_id}_quant_{year_quarter}"
        # Idempotent: if same item already exists, merge proposals
        if item_id in self.items:
            existing = self.items[item_id]
            existing.proposed_by_master.update(proposed_by_master)
            existing.proposed_rationale.update(proposed_rationale)
            return item_id
        self.items[item_id] = AgendaItem(
            item_id=item_id,
            cluster_id=cluster_id,
            item_type="quant_upgrade",
            canonical_claim=canonical_claim,
            rule_subject=rule_subject,
            current_layer0_value=str(current_threshold),
            proposed_by_master=proposed_by_master,
            proposed_rationale=proposed_rationale,
            created_at_debate_id=current_debate_id,
        )
        return item_id

    def add_severity_upgrade(self, cluster_id: str, current_severity: str,
                              proposed_by_master: dict, proposed_rationale: dict,
                              canonical_claim: str, rule_subject: str,
                              current_debate_id: str) -> str:
        year_quarter = self._year_quarter_from_debate_id(current_debate_id)
        item_id = f"agenda_{cluster_id}_severity_{year_quarter}"
        if item_id in self.items:
            existing = self.items[item_id]
            existing.proposed_by_master.update(proposed_by_master)
            existing.proposed_rationale.update(proposed_rationale)
            return item_id
        self.items[item_id] = AgendaItem(
            item_id=item_id,
            cluster_id=cluster_id,
            item_type="severity_upgrade",
            canonical_claim=canonical_claim,
            rule_subject=rule_subject,
            current_layer0_value=current_severity,
            proposed_by_master=proposed_by_master,
            proposed_rationale=proposed_rationale,
            created_at_debate_id=current_debate_id,
        )
        return item_id

    def resolve_item(self, cluster_id: str, item_type: str,
                     new_layer0_value: str, resolved_at_debate_id: str,
                     resolution_note: str) -> None:
        """Mark all active items matching (cluster_id, item_type) as resolved."""
        for item in self.items.values():
            if item.status != "active":
                continue
            if item.cluster_id == cluster_id and item.item_type == item_type:
                item.status = "resolved"
                item.resolved_at_debate_id = resolved_at_debate_id
                item.resolution_note = f"Layer 0 now = {new_layer0_value}. {resolution_note}"

    def mark_stale_and_demote(self, current_debate_id: str,
                               age_quarters_threshold: int = STALE_QUARTERS) -> dict:
        """Increment quarters_unresolved for active items; demote to dormant at threshold."""
        demoted: list[str] = []
        still_active: list[str] = []
        for item in list(self.items.values()):
            if item.status != "active":
                continue
            item.quarters_unresolved += 1
            if item.quarters_unresolved >= age_quarters_threshold:
                item.status = "dormant"
                demoted.append(item.item_id)
            else:
                still_active.append(item.item_id)
        return {"demoted": demoted, "still_active": still_active}

    def get_mini_debate_input(self) -> list[dict]:
        """For T1/T4 triggers, return active + stale items as mini-debate input."""
        out = []
        for item in self.items.values():
            if item.status in ("active", "stale"):
                out.append({
                    "item_id": item.item_id,
                    "cluster_id": item.cluster_id,
                    "item_type": item.item_type,
                    "canonical_claim": item.canonical_claim,
                    "current_layer0_value": item.current_layer0_value,
                    "proposed_by_master": item.proposed_by_master,
                })
        return out

    def active_count(self) -> int:
        return sum(1 for v in self.items.values() if v.status == "active")

    # ─── Helpers ───

    def _year_quarter_from_debate_id(self, debate_id: str) -> str:
        """Extract YYYY-Qn from debate_id like '2026-04-21_manual' → '2026Q2'."""
        m = re.match(r"^(\d{4})-(\d{2})", debate_id)
        if not m:
            now = datetime.now()
            return f"{now.year}Q{(now.month - 1) // 3 + 1}"
        year = m.group(1)
        month = int(m.group(2))
        quarter = (month - 1) // 3 + 1
        return f"{year}Q{quarter}"
